export { ReactComponent as AddFileIcon } from './add-file.svg'
export { ReactComponent as RemoveFileIcon } from './remove-file.svg'
export { ReactComponent as FileTextIcon } from './file-text.svg'
// export { ReactComponent as AddFileIcon } from './add-file.svg'
// export { ReactComponent as AddFileIcon } from './add-file.svg'
