export { ReactComponent as AddFileIcon } from 'ui/add-file.svg'
export { ReactComponent as RemoveFileIcon } from 'ui/remove-file.svg'
export { ReactComponent as FileTextIcon } from 'ui/file-text.svg'
export { ReactComponent as EditingIcon } from 'ui/editing-file.svg'
export { ReactComponent as SavingIcon } from 'ui/saving-file.svg'
export { ReactComponent as SavedIcon } from 'ui/saved-file.svg'
